// Verifies the vendored Pulseboard SDK v3 artifact (Chris0Jeky/Pulseboard observatory/docs/SDK.md):
// the bytes match the lock, the artifact is the unedited builder output for this project, it carries no
// server-only constants, and in a fake browser it defines `window.Pulseboard` without throwing and makes
// no network request until its notice is on screen. Full host CI remains required.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import vm from 'node:vm';

const COLLECTOR = 'https://pulseboard-observatory.commit-atlas.workers.dev';
const ORIGIN = 'https://commit-atlas.commit-atlas.workers.dev';
const root = new URL('../', import.meta.url);
const lock = JSON.parse(readFileSync(new URL('observatory.lock.json', root), 'utf8'));
const sha256 = value => createHash('sha256').update(value).digest('hex');

assert.equal(lock.sdk, '3.0.0', 'The lock must record SDK 3.0.0');
const entries = Object.entries(lock.installs ?? {});
assert.equal(entries.length, 1, 'Exactly one installed artifact is expected');
const [[target, entry]] = entries;
assert.equal(target, 'public/pulseboard.js');
assert.equal(entry.project, 'commitatlas');

const code = readFileSync(new URL(target, root), 'utf8');
assert.equal(sha256(code), entry.sha256, `${target} does not match observatory.lock.json`);
assert.ok(!code.includes('\r'), 'The artifact is LF-only');
const header = /^\/\* SPDX-License-Identifier: GPL-3\.0-only\n \* pulseboard-sdk 3\.0\.0 for commitatlas\. Generated by observatory\/adapters\/build-sdk\.mjs; do not edit\.\n \* sha256 of the body below: ([0-9a-f]{64}) \*\/\n/.exec(code);
assert.ok(header, 'The header must name pulseboard-sdk 3.0.0 for commitatlas');
assert.equal(sha256(code.slice(header[0].length)), header[1], 'The artifact body was edited after generation');
assert.ok(code.includes(`"collector":"${COLLECTOR}"`), 'The collector origin must be the Pulseboard observatory');
assert.ok(code.includes(`"origin":"${ORIGIN}"`), 'The registered origin must be the CommitAtlas Worker');
assert.ok(!/MAX_BYTES|MAX_BATCH/.test(code), 'Server-only constants must not be published');

function element(tag, log) {
  const node = {
    tagName: String(tag).toUpperCase(), children: [], attributes: {}, style: {}, listeners: {}, parent: null,
    className: '', textContent: '', type: '', id: '', checked: false, disabled: false,
    set innerHTML(_) { throw new Error('innerHTML is forbidden'); },
    get innerHTML() { return ''; },
    setAttribute(name, value) { node.attributes[name] = String(value); },
    getAttribute(name) { return node.attributes[name] ?? null; },
    removeAttribute(name) { delete node.attributes[name]; },
    append(...nodes) { for (const n of nodes) { n.parent = node; node.children.push(n); log.push('dom'); } },
    appendChild(n) { node.append(n); return n; },
    prepend(...nodes) { for (const n of [...nodes].reverse()) { n.parent = node; node.children.unshift(n); } log.push('dom'); },
    insertBefore(n) { node.prepend(n); return n; },
    remove() { if (node.parent) node.parent.children.splice(node.parent.children.indexOf(node), 1); node.parent = null; },
    focus() {},
    contains() { return false; },
    addEventListener(type, fn) { (node.listeners[type] ||= []).push(fn); },
    removeEventListener(type, fn) { node.listeners[type] = (node.listeners[type] || []).filter(f => f !== fn); },
    emit(type, event = {}) { for (const fn of [...(node.listeners[type] || [])]) fn({ type, ...event }); },
  };
  return node;
}

function storage() {
  const map = new Map();
  return { getItem: k => (map.has(k) ? map.get(k) : null), setItem: (k, v) => { map.set(k, String(v)); }, removeItem: k => { map.delete(k); } };
}

/** A fake page mid-parse (`readyState: loading`), the state a deferred script can meet. */
function page({ origin = ORIGIN, nav = {}, holder = true } = {}) {
  const log = [];
  const document = element('#document', log);
  const body = element('body', log);
  const placeholder = holder ? element('div', log) : null;
  if (placeholder) { placeholder.style.height = '2.5rem'; body.children.push(placeholder); placeholder.parent = body; }
  Object.assign(document, {
    body, referrer: '', readyState: 'loading', visibilityState: 'visible',
    documentElement: { scrollHeight: 2000, clientHeight: 800, scrollTop: 0 },
    createElement: tag => element(tag, log),
    querySelector: selector => (selector === '[data-pulseboard-bar]' ? placeholder : null),
  });
  const calls = [];
  const window = Object.assign(element('window', log), {
    document, navigator: { ...nav }, localStorage: storage(), sessionStorage: storage(),
    innerWidth: 1280, innerHeight: 800, scrollY: 0,
    location: { origin, protocol: new URL(origin).protocol, href: `${origin}/studio?user=private-handle`, search: '?user=private-handle' },
    AbortController, TextEncoder,
    crypto: { randomUUID: () => '00000000-0000-4000-8000-000000000001' },
    performance: { now: () => 0, getEntriesByType: () => [] },
    matchMedia: () => ({ matches: false }),
    setTimeout: () => 1, clearTimeout() {},
    fetch(url, init = {}) { calls.push({ url: String(url), init }); log.push('fetch'); return new Promise(() => {}); },
  });
  window.globalThis = window;
  window.window = window;
  Object.assign(window, { URL, URLSearchParams, Object, JSON, Math, Date, Number, String, Array, Set, Map, Promise, Uint8Array, TypeError, Error, RegExp });
  vm.createContext(window);
  return { window, document, body, placeholder, calls, log };
}

// 1. On the registered origin: the API exists at once, but nothing is drawn or sent before DOMContentLoaded.
{
  const h = page();
  assert.doesNotThrow(() => vm.runInContext(code, h.window));
  const api = h.window.Pulseboard;
  assert.equal(api?.version, '3.0.0', 'window.Pulseboard must be defined');
  assert.deepEqual(Object.keys(api), ['version', 'route', 'count', 'track', 'consent']);
  assert.equal(h.calls.length, 0, 'No network call before mount');
  assert.equal(h.placeholder.children.length, 0, 'The notice waits for the DOM');
  h.document.emit('DOMContentLoaded');
  assert.equal(h.placeholder.children.length, 1, 'The bar renders into the reserved placeholder');
  assert.equal(h.placeholder.children[0].className.split(' ').includes('pb-bar'), true);
  assert.ok(h.calls.some(call => call.url === `${COLLECTOR}/v1/consent/commitatlas`), 'the region hint is requested after mount');
  const firstFetch = h.log.indexOf('fetch');
  assert.ok(firstFetch === -1 || firstFetch > h.log.indexOf('dom'), 'The notice is on screen before any request');
  for (const call of h.calls) {
    assert.ok(call.url.startsWith(`${COLLECTOR}/`), `unexpected request target ${call.url}`);
    assert.doesNotMatch(JSON.stringify(call.init.body ?? ''), /private-handle|studio\?/, 'no page URL or query leaves the page');
  }
  // Unregistered routes fold to `other`; unknown count events are dropped; nothing throws into the host.
  assert.doesNotThrow(() => api.route('studio'));
  assert.equal(api.count('not.registered'), false);
  assert.doesNotThrow(() => api.track('card.exported', { format: 'markdown', theme: 'ember' }));
}

// 2. Off the registered origin, or under automation: defined, silent, never mounted.
for (const options of [{ origin: 'https://example.test' }, { nav: { webdriver: true } }]) {
  const h = page(options);
  assert.doesNotThrow(() => vm.runInContext(code, h.window));
  assert.equal(h.window.Pulseboard?.version, '3.0.0');
  h.document.emit('DOMContentLoaded');
  assert.equal(h.calls.length, 0, `no request for ${JSON.stringify(options)}`);
  assert.equal(h.placeholder.children.length, 0, `no notice for ${JSON.stringify(options)}`);
}

console.log('Pulseboard SDK 3.0.0 artifact: hash, header, collector, and quiet-until-mounted runtime passed. Full host CI remains required.');
